const quizData = [
    {"ex" : "一番上の,最上級の", "word" : "top"},
    {"ex" : "観光", "word" : "sightseeing"},
    {"ex" : "行く(活用も)", "word" : "go-went-gone-going"},
    {"ex" : "無数の", "word" : "countless"},
    {"ex" : "建設,建造", "word" : "construction"},
    {"ex" : "寄贈者", "word" : "donor"},
    {"ex" : "はっきりとした", "word" : "sharp"},
    {"ex" : "対照,対比", "word" : "contrast"},
    {"ex" : "異国風の", "word" : "exotic"},
    {"ex" : "(人の)心を引きつける", "word" : "appeal"},

    {"ex" : "近頃は", "word" : "nowadays"},
    {"ex" : "探す,探求する(活用も)", "word" : "seek-sought-sought-seeking"},
    {"ex" : "~を知っている(活用も)", "word" : "know-knew-known-knowing"},
    {"ex" : "ジャパウ", "word" : "japow"},
    {"ex" : "立つ(活用も)", "word" : "stand-stood-stood-standing"},
    {"ex" : "スキーヤー", "word" : "skier"},
    {"ex" : "スノーボーダー", "word" : "snowboarder"},
    {"ex" : "来る(活用も)", "word" : "come-came-come-coming"},
    {"ex" : "メッカ(聖地)", "word" : "mecca"},

    {"ex" : "アニメ", "word" : "anime"},
    {"ex" : "神聖な", "word" : "holy"},
    {"ex" : "忍者", "word" : "ninja"},
    {"ex" : "~を着る(活用も)", "word" : "wear-wore-worn-wearing"},
    {"ex" : "衣装", "word" : "costume"},
    {"ex" : "~を受ける(活用も)", "word" : "take-took-taken-taking"},
    {"ex" : "訓練,修行", "word" : "training"},
    {"ex" : "授業,けいこ", "word" : "lesson"},
    {"ex" : "すし", "word" : "sushi"},
    {"ex" : "作ること", "word" : "making"},
    {"ex" : "食事", "word" : "meal"},

    {"ex" : "インタビューアー", "word" : "interviewer"},
    {"ex" : "農場", "word" : "farm"},
    {"ex" : "グアム島", "word" : "Guam"},
    {"ex" : "思いがけなく", "word" : "unexpectedly"},
    {"ex" : "勝つ(活用も)", "word" : "win-won-won-winning"},
    {"ex" : "若い人", "word" : "youth"},
    {"ex" : "~を建てる,造る", "word" : "build-built-built-building"},
    {"ex" : "牛舎", "word" : "cowshed"},
    {"ex" : "することができる", "word" : "able"}
];